# Generated by Django 5.1.6 on 2025-03-13 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_logininfo_options_user_address_user_bio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logininfo',
            name='ip_address',
        ),
        migrations.AddField(
            model_name='logininfo',
            name='device_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
